apiVersion: v1
kind: Service
metadata:
  name: mattermost-db
spec:
  ports:
  - port: 5432
  selector:
    app: mattermost-db
  clusterIP: None
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mattermost-db
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi
---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: mattermost-db
spec:
  selector:
    matchLabels:
      app: mattermost-db
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: mattermost-db
    spec:
      containers:
      - image: postgres:9
        name: mattermost-db
        env:
        - name: POSTGRES_USER
          valueFrom:
              configMapKeyRef:
                  name: mattermost-db
                  key: username
        - name: POSTGRES_PASSWORD
          valueFrom:
              configMapKeyRef:
                  name: mattermost-db
                  key: password
        ports:
        - containerPort: 5432
          name: mattermost-db
        volumeMounts:
        - name: mattermost-db-init-script
          mountPath: /docker-entrypoint-initdb.d
        - name: mattermost-db
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: mattermost-db-init-script
        configMap:
            name: mattermost-db
            items:
            - key: init-script
              path: init-user.sh
      - name: mattermost-db
        persistentVolumeClaim:
          claimName: mattermost-db
